[package]
name = "librewave-platform-linux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
librewave-device = { path = "../librewave-device" }
rusb = "0.9.4"

[lints]
workspace = true
