[package]
name = "librewave-platform-linux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
alsa = "=0.12.1"
libc.workspace = true
librewave-core = { path = "../librewave-core" }
librewave-device = { path = "../librewave-device" }
librewave-engine = { path = "../librewave-engine" }
librewave-ipc = { path = "../librewave-ipc" }
librewave-protocol = { path = "../librewave-protocol" }
pipewire = "=0.9.2"
rusb = "0.9.4"

[build-dependencies]
cc = "1.4.3"
pkg-config = "0.3.34"

[lints]
workspace = true
