[package]
name = "librewave-platform-linux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
libc.workspace = true
librewave-core = { path = "../librewave-core" }
librewave-device = { path = "../librewave-device" }
librewave-ipc = { path = "../librewave-ipc" }
librewave-protocol = { path = "../librewave-protocol" }
rusb = "0.9.4"

[lints]
workspace = true
