[package]
name = "librewave-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Portable realtime mixer engine for LibreWave"

[dependencies]
librewave-core = { path = "../librewave-core" }
rubato = { version = "=4.0.0", default-features = false }

[lints]
workspace = true
