[package]
name = "librewave"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Optional LibreWave desktop application"

[dependencies]
librewave-ui = { path = "../librewave-ui", features = ["gpui"] }

[lints]
workspace = true
